#(주)한글과컴퓨터의 한컴오피스 hwp 문서 파일 구조 공개정책에 따라 이루어졌습니다.
#이렇게 말하면 libhwp 개발자가 (주)한글과컴퓨터社와 어떤 관계가 있는 것처럼 오해받을 수 있지만
#hwp 스펙 문서 11쪽 저작권 관련 내용을 보면 이렇게 표시하라고 해서 이렇게 표시했을 뿐입니다.
#libhwp는 (주)한글과컴퓨터社가 만든 것이 아니며, (주)한글과컴퓨터社가 지원하지 않으며, (주)한글과컴퓨터社가 유지보수하지 않습니다.
#Note that libhwp is not manufactured, approved, supported, maintained by Hancom Inc.
#libhwp 개발자는 (주)한글과컴퓨터社와 아무런 관련이 없습니다.
#libhwp 및 libhwp 관련 문서 내용을 사용하여 발생된 모든 결과에 대하여 책임지지 않습니다.
#NO WARRANTY

HWPTAG_BEGIN = 0x010 # 16
HWPTAG_DOCUMENT_PROPERTIES = HWPTAG_BEGIN

HWPTAGS = {
	# docinfo
	HWPTAG_BEGIN   => :HWPTAG_DOCUMENT_PROPERTIES,
	HWPTAG_BEGIN+1 => :HWPTAG_ID_MAPPINGS,
	HWPTAG_BEGIN+2 => :HWPTAG_BIN_DATA,
	HWPTAG_BEGIN+3 => :HWPTAG_FACE_NAME,
	HWPTAG_BEGIN+4 => :HWPTAG_BORDER_FILL,
	HWPTAG_BEGIN+5 => :HWPTAG_CHAR_SHAPE,
	HWPTAG_BEGIN+6 => :HWPTAG_TAB_DEF,
	HWPTAG_BEGIN+7 => :HWPTAG_NUMBERING,
	HWPTAG_BEGIN+8 => :HWPTAG_BULLET,
	HWPTAG_BEGIN+9 => :HWPTAG_PARA_SHAPE,
	HWPTAG_BEGIN+10 => :HWPTAG_STYLE,
	HWPTAG_BEGIN+11 => :HWPTAG_DOC_DATA,
	HWPTAG_BEGIN+12 => :HWPTAG_DISTRIBUTE_DOC_DATA,
	HWPTAG_BEGIN+13 => :RESERVED,
	HWPTAG_BEGIN+14 => :HWPTAG_COMPATIBLE_DOCUMENT,
	HWPTAG_BEGIN+15 => :HWPTAG_LAYOUT_COMPATIBILITY,

	HWPTAG_BEGIN+78 => :HWPTAG_FORBIDDEN_CHAR,

	# section
	HWPTAG_BEGIN+50 => :HWPTAG_PARA_HEADER,	# 66
	HWPTAG_BEGIN+51 => :HWPTAG_PARA_TEXT,
	HWPTAG_BEGIN+52 => :HWPTAG_PARA_CHAR_SHAPE,
	HWPTAG_BEGIN+53 => :HWPTAG_PARA_LINE_SEG,
	HWPTAG_BEGIN+54 => :HWPTAG_PARA_RANGE_TAG,
	HWPTAG_BEGIN+55 => :HWPTAG_CTRL_HEADER,
	HWPTAG_BEGIN+56 => :HWPTAG_LIST_HEADER,
	HWPTAG_BEGIN+57 => :HWPTAG_PAGE_DEF,
	HWPTAG_BEGIN+58 => :HWPTAG_FOOTNOTE_SHAPE,
	HWPTAG_BEGIN+59 => :HWPTAG_PAGE_BORDER_FILL,
	HWPTAG_BEGIN+60 => :HWPTAG_SHAPE_COMPONENT,
	HWPTAG_BEGIN+61 => :HWPTAG_TABLE,
	HWPTAG_BEGIN+62 => :HWPTAG_SHAPE_COMPONENT_LINE,
	HWPTAG_BEGIN+63 => :HWPTAG_SHAPE_COMPONENT_RECTANGLE,
	HWPTAG_BEGIN+64 => :HWPTAG_SHAPE_COMPONENT_ELLIPSE,
	HWPTAG_BEGIN+65 => :HWPTAG_SHAPE_COMPONENT_ARC,
	HWPTAG_BEGIN+66 => :HWPTAG_SHAPE_COMPONENT_POLYGON,
	HWPTAG_BEGIN+67 => :HWPTAG_SHAPE_COMPONENT_CURVE,
	HWPTAG_BEGIN+68 => :HWPTAG_SHAPE_COMPONENT_OLE,
	HWPTAG_BEGIN+69 => :HWPTAG_SHAPE_COMPONENT_PICTURE,
	HWPTAG_BEGIN+70 => :HWPTAG_SHAPE_COMPONENT_CONTAINER,
	HWPTAG_BEGIN+71 => :HWPTAG_CTRL_DATA,
	HWPTAG_BEGIN+72 => :HWPTAG_EQEDIT,
	HWPTAG_BEGIN+73 => :RESERVED,
	HWPTAG_BEGIN+74 => :HWPTAG_SHAPE_COMPONENT_TEXTART,
	HWPTAG_BEGIN+75 => :HWPTAG_FORM_OBJECT,
	HWPTAG_BEGIN+76 => :HWPTAG_MEMO_SHAPE,
	HWPTAG_BEGIN+77 => :HWPTAG_MEMO_LIST,

	HWPTAG_BEGIN+79 => :HWPTAG_CHART_DATA,

	HWPTAG_BEGIN+99 => :HWPTAG_SHAPE_COMPONENT_UNKNOWN	# 115
}

HISTORY_TAGS = {
	0x10 => :HISTORY_RECORD_TYPE_STAG,
	0x11 => :HISTORY_RECORD_TYPE_ETAG,
	0x20 => :HISTORY_RECORD_TYPE_VERSION,
	0x21 => :HISTORY_RECORD_TYPE_DATE,
	0x22 => :HISTORY_RECORD_TYPE_WRITER,
	0x23 => :HISTORY_RECORD_TYPE_DESCRIPTION,
	0x30 => :HISTORY_RECORD_TYPE_DIFFDATA,
	0x31 => :HISTORY_RECORD_TYPE_LASTDOCDATA
}
